apiVersion: optimize.stormforge.io/v1beta2
kind: Experiment
metadata:
  name: voting-app-example
  labels:
    stormforge.io/application: 'voting-app'
    stormforge.io/scenario: 'locust'
spec:
  optimization:
  - name: "experimentBudget"
    value: "100"
  parameters:
  - name: worker_cpu
    baseline: 1000
    min: 100
    max: 1000
  - name: voting_memory
    baseline: 2000
    min: 200
    max: 2000
  - name: voting_cpu
    baseline: 1000
    min: 100
    max: 1000
  - name: voting_replicas
    baseline: 3
    min: 1
    max: 4
  - name: db_memory
    baseline: 2000
    min: 200
    max: 2000
  metrics:
  - name: throughput
    minimize: false
    type: jsonpath
    query: '{.total}'
    url: 'http://result-exporter:5000/metrics'
  - name: cost
    minimize: true
    # Note that these cost weights are specific to GKE and represent $22/month/cpu and $3/month/GB
    query: '{{resourceRequests .Pods "cpu=0.022,memory=0.000000000003"}}'
    target:
      kind: PodList
      matchLabels:
        app: voting-app
  patches:
  - targetRef:
      name: worker
      apiVersion: apps/v1
      kind: Deployment
    patch: |
      spec:
        template:
          spec:
            containers:
            - name: worker
              resources:
                limits:
                  cpu: "{{ .Values.worker_cpu }}m"
                requests:
                  cpu: "{{ .Values.worker_cpu }}m"
  - targetRef:
      name: voting-service
      apiVersion: apps/v1
      kind: Deployment
    patch: |
      spec:
        replicas: {{ .Values.voting_replicas }}
        template:
          spec:
            containers:
            - name: voting-service
              resources:
                limits:
                  cpu: "{{ .Values.voting_cpu }}m"
                  memory: "{{ .Values.voting_memory }}Mi"
                requests:
                  cpu: "{{ .Values.voting_cpu }}m"
                  memory: "{{ .Values.voting_memory }}Mi"
  - targetRef:
      name: db
      apiVersion: apps/v1
      kind: Deployment
    patch: |
      spec:
        template:
          spec:
            containers:
            - name: db
              resources:
                limits:
                  memory: "{{ .Values.db_memory }}Mi"
                requests:
                  memory: "{{ .Values.db_memory }}Mi"
  trialTemplate:
    spec:
      jobTemplate:
        spec:
          template:
            spec:
              containers:
              - name: locust
                image: grubykarol/locust:0.12.0-python3.7-alpine3.10
                command: ["/usr/local/bin/locust"]
                args: ["--locustfile=/locust-tasks/locustfile.py", "--no-web", "--host=http://voting-service",
                  "--clients=200", "--hatch-rate=20", "--run-time=300", "--exit-code-on-error=0"]
                volumeMounts:
                - name: locust
                  mountPath: /locust-tasks/locustfile.py
                  subPath: locustfile.py
              volumes:
              - name: locust
                configMap:
                  name: locust
