apiVersion: apps.redskyops.dev/v1alpha1
kind: Application
metadata:
  name: votingapp

# The resources identify where the manifests representing the application live.
# This is roughly the same as a Kustomize resources block, so you can use files,
# directories, URLs, Git repos, etc.
resources:
- https://github.com/thestormforge/examples/voting-webapp/application

# This section configures the objectives of optimization
# We want to minimize both cost and latency
objectives:
- goals:
  - name: cost-gcp # Also "cost", "cost-aws", "cpu", ...
  - name: p95-latency
    optimize: false
  - name: p99-latency
    max: 500

# Control over the discovery of parameters, also optional
# The default is to generate patches for all deployments and stateful sets
# Here we decide to only optimize the voting service respon
parameters:
  containerResources:
    labelSelector: component=voting-service
  replicas:
    labelSelector: component=voting-service

# This section configures the scenarios of load generation
scenarios:
- name: 100-clients
  locust:
    users: 100
    spawnRate: 20
    locustfile: locustfile.py

# The host for the locust trial job
ingress:
  url:  http://voting-service

