apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: voting-hpa
  labels:
    app: voting-app
    component: hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voting-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
