---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testapp-with-cli-v3-2022-4
  namespace: default
rules:
- resources:
  - deployments
  apiGroups:
  - apps
  verbs:
  - get
  - patch
- resources:
  - pods
  apiGroups:
  - ""
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testapp-with-cli-v3-2022-4
  namespace: default
roleRef:
  name: testapp-with-cli-v3-2022-4
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: optimize-pro-controller
  namespace: stormforge-system
  kind: ServiceAccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testapp-with-cli-v3-2022-4-setup
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testapp-with-cli-v3-2022-4-setup
  namespace: default
rules:
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - create
  - delete
  - list
  - get
  - update
- resources:
  - replicasets
  apiGroups:
  - apps
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testapp-with-cli-v3-2022-4-setup
  namespace: default
roleRef:
  name: testapp-with-cli-v3-2022-4-setup
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: testapp-with-cli-v3-2022-4-setup
  namespace: default
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optimize-prometheus-265e20
rules:
- resources:
  - clusterroles
  - clusterrolebindings
  apiGroups:
  - rbac.authorization.k8s.io
  verbs:
  - get
  - create
  - delete
- resources:
  - serviceaccounts
  - services
  - configmaps
  apiGroups:
  - ""
  verbs:
  - get
  - create
  - delete
- resources:
  - deployments
  apiGroups:
  - apps
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  apiGroups:
  - ""
  verbs:
  - list
  - watch
  - get
- resources:
  - pods
  apiGroups:
  - ""
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: optimize-setup-prometheus-265e20
roleRef:
  name: optimize-prometheus-265e20
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: testapp-with-cli-v3-2022-4-setup
  namespace: default
  kind: ServiceAccount
