apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../webapp/voting-webapp/application/manifests
- ingress.yaml
- hpa.yaml

patchesStrategicMerge:
- node-port-patch.yaml
