---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: curl-testapp
  namespace: default
rules:
- resources:
  - deployments
  apiGroups:
  - apps
  verbs:
  - get
  - patch
- resources:
  - pods
  apiGroups:
  - ""
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: curl-testapp
  namespace: default
roleRef:
  name: curl-testapp
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: optimize-pro-controller
  namespace: stormforge-system
  kind: ServiceAccount
