apiVersion: optimize.stormforge.io/v1beta2
kind: Experiment
metadata:
  name: voting-sf-vhs-experiment
  namespace: default
  labels:
    stormforge.io/application: voting-sf-example-vhs
    stormforge.io/scenario: standard
spec:
  parameters:
  - name: memory
    baseline: 2098
    min: 1024
    max: 4096
  - name: cpu
    baseline: 750
    min: 500
    max: 1000
  - name: replicas
    baseline: 2
    min: 1
    max: 3
  metrics:
  - name: p50-latency
    type: prometheus
    minimize: true
    optimize: false
    query: scalar(median{job="trialRun",instance="{{ .Trial.Name }}"})
  - name: p95-latency
    type: prometheus
    max: "500"
    minimize: true
    query: scalar(percentile_95{job="trialRun",instance="{{ .Trial.Name }}"})
  - name: p99-latency
    type: prometheus
    minimize: true
    optimize: false
    query: scalar(percentile_99{job="trialRun",instance="{{ .Trial.Name }}"})
  - name: cost
    type: prometheus
    minimize: true
    query: ({{ cpuRequests . "app=voting-app" }} * 1) + ({{ memoryRequests . "app=voting-app"
      | GB }} * 1)
  - name: cost-cpu-requests
    type: prometheus
    minimize: true
    optimize: false
    query: '{{ cpuRequests . "app=voting-app" }}'
  - name: cost-memory-requests
    type: prometheus
    minimize: true
    optimize: false
    query: '{{ memoryRequests . "app=voting-app" | GB }}'
  patches:
  - targetRef:
      name: voting-service
      apiVersion: apps/v1
      kind: Deployment
    patch: |
      spec:
        replicas: {{ .Values.replicas }}
        template:
          spec:
            containers:
            - name: voting-service
              resources:
                limits:
                  memory: '{{ .Values.memory }}M'
                  cpu: '{{ .Values.cpu }}m'
                requests:
                  memory: '{{ .Values.memory }}M'
                  cpu: '{{ .Values.cpu }}m'
  trialTemplate:
    metadata:
      labels:
        stormforge.io/application: voting-sf-example-vhs
        stormforge.io/scenario: standard
    spec:
      jobTemplate:
        metadata:
          labels:
            stormforge.io/application: voting-sf-example-vhs
            stormforge.io/scenario: standard
        spec:
          template:
            metadata:
              labels:
                stormforge.io/application: voting-sf-example-vhs
                stormforge.io/scenario: standard
            spec:
              initContainers:
              - name: vhstoforge
                image: ubuntu:20.10
                command:
                - /bin/bash
                args:
                - -x
                - /har/har2testcase.sh
                env:
                - name: GCS_BUCKET
                  value: vhsdemo
                - name: GCS_OBJECT
                  value: 1lnFKPQEk4a9d9BJBfhPWhiL3hk
                - name: HAR_LIMIT
                  value: "18000000"
                - name: TEST_CASE_FILE
                  value: /jshar/testcase.js
                - name: INGRESS_ADDRESS
                  value: 34.117.104.17
                - name: STORMFORGER_JWT
                  valueFrom:
                    secretKeyRef:
                      name: stormforger-service-account
                      key: accessToken
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /root/.config/gcloud/service-account.json
                volumeMounts:
                - name: jshar
                  mountPath: /jshar
                - name: harutils
                  mountPath: /har
                - name: cloud-credentials
                  mountPath: /root/.config/gcloud
              containers:
              - name: stormforger
                image: thestormforge/optimize-trials:v0.0.1-stormforger
                env:
                - name: TITLE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: TEST_CASE
                  value: sf_sandbox/voting-sf-example-vhs2
                - name: TEST_CASE_FILE
                  value: /jshar/testcase.js
                - name: TARGET
                  value: 34.117.104.17
                - name: STORMFORGER_JWT
                  valueFrom:
                    secretKeyRef:
                      name: stormforger-service-account
                      key: accessToken
                volumeMounts:
                - name: jshar
                  readOnly: true
                  mountPath: /jshar
              volumes:
              - name: jshar
                emptyDir: {}
              - name: harutils
                configMap:
                  name: harutils
              - name: cloud-credentials
                secret:
                  secretName: gcs-creds
      setupServiceAccountName: stormforge-setup
      setupTasks:
      - name: monitoring
        args:
        - prometheus
        - $(MODE)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stormforge-setup
  namespace: default
  labels:
    stormforge.io/application: 'voting-sf-example-vhs'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stormforge-prometheus-6ea045
  labels:
    stormforge.io/application: 'voting-sf-example-vhs'
rules:
- resources:
  - clusterroles
  - clusterrolebindings
  apiGroups:
  - rbac.authorization.k8s.io
  verbs:
  - get
  - create
  - delete
- resources:
  - serviceaccounts
  - services
  - configmaps
  apiGroups:
  - ""
  verbs:
  - get
  - create
  - delete
- resources:
  - deployments
  apiGroups:
  - apps
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  apiGroups:
  - ""
  verbs:
  - list
  - watch
  - get
- resources:
  - pods
  apiGroups:
  - ""
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stormforge-setup-prometheus-6ea045
  labels:
    stormforge.io/application: 'voting-sf-example-vhs'
roleRef:
  name: stormforge-prometheus-6ea045
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: stormforge-setup
  namespace: default
  kind: ServiceAccount
