apiVersion: optimize.stormforge.io/v1beta2
kind: Experiment
metadata:
  name: parallel-postgres
  labels:
    stormforge.io/application: 'parallel-postgres'
    stormforge.io/scenario: 'pgbench'
spec:
  replicas: 4
  optimization:
  - name: "experimentBudget"
    value: "40"
  parameters:
  - name: memory
    baseline: 4000
    min: 500
    max: 4000
  - name: cpu
    baseline: 4000
    min: 100
    max: 4000
  metrics:
  - name: duration
    minimize: true
    query: "{{duration .StartTime .CompletionTime}}"
  - name: cost
    minimize: true
    query: "{{div (add (mul .Values.cpu 22) (mul .Values.memory 3)) 1000}}"
  patches:
  - targetRef:
      name: postgres
      apiVersion: apps/v1
      kind: Deployment
    patch: |
      spec:
        template:
          spec:
            containers:
            - name: postgres
              resources:
                limits:
                  cpu: "{{ .Values.cpu }}m"
                  memory: "{{ .Values.memory }}Mi"
                requests:
                  cpu: "{{ .Values.cpu }}m"
                  memory: "{{ .Values.memory }}Mi"
  namespaceSelector:
    matchLabels:
      experiment: parallel-postgres
  trialTemplate:
    spec:
      jobTemplate:
        spec:
          template:
            spec:
              containers:
              - name: pgbench
                image: crunchydata/crunchy-pgbench:centos7-11.4-2.4.1
                envFrom:
                - secretRef:
                    name: postgres-secret
