apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: elasticsearch-example-workflow
spec:
  entrypoint: run-all
  templates:
  - name: run-all
    steps:
      - - name: rally-config-create
          template: rally-config-create
      - - name: elasticsearch-example-create
          template: elasticsearch-example-create
  - name: rally-config-create
    resource:
      action: apply
      setOwnerReference: true
      manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          namespace: default
          name: rally-ini
        data:
          rally-config: |
            [meta]
            config.version = 17

            [system]
            env.name = docker

            [node]
            root.dir = /rally/.rally/benchmarks
            src.root.dir = /rally/.rally/benchmarks/src

            [source]
            remote.repo.url = https://github.com/elastic/elasticsearch.git
            elasticsearch.src.subdir = elasticsearch

            [benchmarks]
            local.dataset.cache = /rally/.rally/benchmarks/data

            [reporting]
            datastore.type = elasticsearch
            datastore.host = elasticsearch-master
            datastore.port = 9200
            datastore.secure = False
            datastore.user =
            datastore.password =

            [tracks]
            default.url = https://github.com/elastic/rally-tracks

            [teams]
            default.url = https://github.com/elastic/rally-teams

            [defaults]
            preserve_benchmark_candidate = False

            [distributions]
            release.cache = true
  - name: elasticsearch-example-create
    resource:
      action: apply
      setOwnerReference: true
      manifest: |
        apiVersion: redskyops.dev/v1alpha1
        kind: Experiment
        metadata:
          namespace: default
          name: elasticsearch-example
        spec:
          optimization:
          - name: "experimentBudget"
            value: "80"
          parameters:
          - name: memory
            min: 8000
            max: 16000
            baseline: 8000
          - name: cpu
            min: 6000
            max: 8000
            baseline: 8000
          - name: heap_percent
            min: 20
            max: 80
            baseline: 50
          metrics:
          - name: duration
            minimize: true
            query: "{{duration .StartTime .CompletionTime}}"
          - name: cost
            minimize: true
            type: pods
            # Note that these cost weights are specific to GKE and represent $22/month/cpu and $3/month/GB
            query: '{{resourceRequests .Pods "cpu=0.022,memory=0.000000000003"}}'
            selector:
              matchLabels:
                app: elasticsearch-master
          template: # trial
            spec:
              readinessGates:
              - kind: StatefulSet
                apiVersion: apps/v1
                name: elasticsearch-master
                conditionTypes:
                - redskyops.dev/app-ready
                initialDelaySeconds: 30
                periodSeconds: 15
                failureThreshold: 60
              setupTasks:
              - name: elasticsearch
                helmChart: elasticsearch
                helmChartVersion: 7.9.2
                helmRepository: https://helm.elastic.co
                helmValues:
                - name: clusterName
                  value: elasticsearch
                - name: replicas
                  value: 1
                - name: resources.limits.cpu
                  value: "{{ .Values.cpu }}m"
                - name: resources.limits.memory
                  value: "{{ .Values.memory }}Mi"
                - name: resources.requests.cpu
                  value: "{{ .Values.cpu }}m"
                - name: resources.requests.memory
                  value: "{{ .Values.memory }}Mi"
                - name: esJavaOpts
                  value: "-Djava.net.preferIPv4Stack=true -Xms{{ percent .Values.memory .Values.heap_percent }}m -Xmx{{ percent .Values.memory .Values.heap_percent }}m"
                - name: persistence.enabled
                  value: "false"
                - name: antiAffinity
                  value: soft
                - name: discovery.type
                  value: single-node
                - name: cluster.initial_master_nodes
                  value: "null"
              setupServiceAccountName: redsky
              template: # job
                spec:
                  activeDeadlineSeconds: 1000
                  template: # pod
                    spec:
                      containers:
                      - image: elastic/rally:2.0.1
                        name: rally
                        args:
                        - --track=geopoint
                        - --target-hosts=elasticsearch-master
                        - --pipeline=benchmark-only
                        - --challenge=append-fast-with-conflicts
                        - --track-params=ingest_percentage:10,bulk_size:50,bulk_indexing_clients:300
                        - --distribution-version=7.9.2
                        volumeMounts:
                          - name: config
                            mountPath: /rally/.rally/rally.ini
                            subPath: rally-config
                      volumes:
                        - name: config
                          configMap:
                            name: rally-ini
