

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: elasticsearch-example-workflow
spec:
  entrypoint: run-all
  templates:
  - name: run-all
    steps:
      - - name: experiment-create
          template: experiment-create
      - - name: trial-create
          template: trial-create
      - - name: trial-wait-for-ready
          template: trial-wait-for-ready
      - - name: trial-wait-for-completion
          template: trial-wait-for-completion
  - name: experiment-create
    container:
      image: 516273174544.dkr.ecr.us-east-1.amazonaws.com/thestormforge-examples
      imagePullPolicy: Always
      command: [sh]
      args:
        - -c
        - "kustomize build .ci/elasticsearch | kubectl -n default apply -f -"
  - name: trial-create
    container:
      image: 516273174544.dkr.ecr.us-east-1.amazonaws.com/thestormforge-examples
      command: [sh]
      args:
        - -c
        - "kubectl -n default get experiment elasticsearch-example -o yaml | redskyctl generate trial --assign cpu=7559 --assign memory=11086 --assign heap_percent=50 -f - | kubectl -n default create -f -"
  - name: trial-wait-for-ready
    container:
      image: 516273174544.dkr.ecr.us-east-1.amazonaws.com/thestormforge-examples
      command: [sh]
      args:
        - -c
        - "kubectl -n default wait trial -l redskyops.dev/experiment=elasticsearch-example --for condition=redskyops.dev/trial-ready  --timeout 180s"
  - name: trial-wait-for-completion
    container:
      image: 516273174544.dkr.ecr.us-east-1.amazonaws.com/thestormforge-examples
      command: [sh]
      args:
        - -c
        - "kubectl -n default wait trial -l redskyops.dev/experiment=elasticsearch-example --for condition=redskyops.dev/trial-ready  --timeout 360s"
