apiVersion: optimize.stormforge.io/v1beta2
kind: Experiment
metadata:
  name: testapp-with-cli-v3-2022-1
  namespace: default
  labels:
    stormforge.io/application: 'stormforger-testapp'
    stormforge.io/scenario: 'scenario1'
  #   stormforge.io/objective: 'duration-vs-cost'
spec:
  optimization:
  - name: experimentBudget
    value: "20"

  parameters:
  - name: cpu
    baseline: 1000
    min: 500
    max: 2000
  - name: memory
    baseline: 2048
    min: 512
    max: 2048

  metrics:
  - name: cost
    minimize: true
    query: '{{ resourceRequests .Target "cpu=0.017,memory=0.000000000003" }}'
    target:
      apiVersion: v1
      kind: PodList
      matchLabels:
        app.kubernetes.io/instance: testapp-example
        app.kubernetes.io/name: testapp
  - name: duration
    minimize: true
    query: '{{ duration .StartTime .CompletionTime }}'

  patches:
  - targetRef:
      name: testapp
      apiVersion: apps/v1
      kind: Deployment
    patch: |
      spec:
        template:
          spec:
            containers:
            - name: testapp
              resources:
                limits:
                  cpu: '{{ .Values.cpu }}m'
                  memory: '{{ .Values.memory }}M'
                requests:
                  cpu: '{{ .Values.cpu }}m'
                  memory: '{{ .Values.memory }}M'

  trialTemplate:
    # metadata:
    #   labels:
    #     stormforge.io/application: 'postgres'
    #     stormforge.io/objective: 'duration-vs-cost'
    #     stormforge.io/scenario: 'pgbench'
    spec:
      initialDelaySeconds: 15
      jobTemplate:
        # metadata:
        #   labels:
        #     stormforge.io/application: 'postgres'
        #     stormforge.io/objective: 'duration-vs-cost'
        #     stormforge.io/scenario: 'pgbench'
        spec:
          setupTasks:
          - name: monitoring
            args:
            - prometheus
            - $(MODE)
          template:
            # metadata:
            #   labels:
            #     stormforge.io/application: 'postgres'
            #     stormforge.io/objective: 'duration-vs-cost'
            #     stormforge.io/scenario: 'pgbench'
            spec:
              containers:
              - name: curl
                image: 155712429589.dkr.ecr.us-east-1.amazonaws.com/stormforge-cli:3.0.0-alpha.5
                env:
                - name: ENABLE_PERFTEST_PREVIEW_COMMANDS
                  value: "true"
                envFrom:
                - secretRef:
                    name: stormforge-v3
                args:
                # NOTE: --metrics-output is automatically activated via ENV variable
                - create
                - test-run
                - "--test-case=testapp_labs_optimize_trial"
                - "--watch-timeout=1h"
                - "--watch"
