apiVersion: redskyops.dev/v1alpha1
kind: Experiment
metadata:
  name: elasticsearch-example
spec:
  optimization:
  - name: "experimentBudget"
    value: "80"
  parameters:
  - name: memory
    min: 1000
    max: 2000
    baseline: 2000
  - name: cpu
    min: 500
    max: 1000
    baseline: 1000
  - name: heap_percent
    min: 20
    max: 80
    baseline: 50
  - name: replicas
    min: 3
    max: 5
    baseline: 3
  metrics:
  - name: duration
    minimize: true
    query: "{{duration .StartTime .CompletionTime}}"
  - name: cost
    minimize: true
    type: pods
    # Note that these cost weights are specific to GKE and represent $22/month/cpu and $3/month/GB
    query: '{{resourceRequests .Pods "cpu=0.022,memory=0.000000000003"}}'
    selector:
      matchLabels:
        app: elasticsearch-master
  template: # trial
    spec:
      readinessGates:
      - kind: StatefulSet
        apiVersion: apps/v1
        name: elasticsearch-master
        conditionTypes:
        - redskyops.dev/app-ready
        InitialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 30
      setupTasks:
      - name: elasticsearch
        helmChart: elasticsearch
        helmChartVersion: 7.9.2
        helmRepository: https://helm.elastic.co
        helmValues:
        - name: cluster.name
          value: rally-demo
        - name: replicas
          value: "{{ .Values.replicas }}"
        - name: resources.limits.cpu
          value: "{{ .Values.cpu }}m"
        - name: resources.limits.memory
          value: "{{ .Values.memory }}Mi"
        - name: resources.requests.cpu
          value: "{{ .Values.cpu }}m"
        - name: resources.requests.memory
          value: "{{ .Values.memory }}Mi"
        - name: esJavaOpts
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ percent .Values.memory .Values.heap_percent }}m -Xmx{{ percent .Values.memory .Values.heap_percent }}m"
        - name: persistence.enabled
          value: "false"
        - name: antiAffinity
          value: soft
      setupServiceAccountName: redsky
      template: # job
        spec:
          template: # pod
            spec:
              activeDeadlineSeconds: 1800
              containers:
              - image: elastic/rally:2.0.1
                name: rally
                args:
                - --track=geopoint
                - --target-hosts=elasticsearch-master
                - --pipeline=benchmark-only
                - --challenge=append-fast-with-conflicts
                - --track-params=ingest_percentage:50
                - --distribution-version=7.9.2
                volumeMounts:
                  - name: config
                    mountPath: /rally/.rally/rally.ini
                    subPath: rally-config
              volumes:
                - name: config
                  configMap:
                    name: rally-ini
