apiVersion: optimize.stormforge.io/v1beta2
kind: Experiment
metadata:
  name: elasticsearch-example
  labels:
    stormforge.io/application: 'elasticsearch'
    stormforge.io/scenario: 'rally'
spec:
  optimization:
  - name: "experimentBudget"
    value: "80"
  parameters:
  - name: memory
    baseline: 2000
    min: 1000
    max: 2000
  - name: cpu
    baseline: 1000
    min: 500
    max: 1000
  - name: heap_percent
    baseline: 50
    min: 20
    max: 80
  - name: replicas
    baseline: 3
    min: 3
    max: 5
  metrics:
  - name: duration
    minimize: true
    query: "{{duration .StartTime .CompletionTime}}"
  - name: cost
    minimize: true
    # Note that these cost weights are specific to GKE and represent $22/month/cpu and $3/month/GB
    query: '{{resourceRequests .Pods "cpu=0.022,memory=0.000000000003"}}'
    target:
      kind: PodList
      matchLabels:
        app: elasticsearch-master
  trialTemplate:
    spec:
      readinessGates:
      - name: elasticsearch-master
        apiVersion: apps/v1
        kind: StatefulSet
        conditionTypes:
        - stormforge.io/app-ready
        failureThreshold: 30
        initialDelaySeconds: 5
        periodSeconds: 5
      jobTemplate:
        spec:
          template:
            spec:
              activeDeadlineSeconds: 1800
              containers:
              - name: rally
                image: elastic/rally:2.0.1
                args:
                - --track=geopoint
                - --target-hosts=elasticsearch-master
                - --pipeline=benchmark-only
                - --challenge=append-fast-with-conflicts
                - --track-params=ingest_percentage:50
                - --distribution-version=7.9.2
                volumeMounts:
                - name: config
                  mountPath: /rally/.rally/rally.ini
                  subPath: rally-config
              volumes:
              - name: config
                configMap:
                  name: rally-ini
      setupServiceAccountName: stormforge
      setupTasks:
      - name: elasticsearch
        helmChart: elasticsearch
        helmChartVersion: 7.9.2
        helmRepository: https://helm.elastic.co
        helmValues:
        - name: cluster.name
          value: rally-demo
        - name: replicas
          value: "{{ .Values.replicas }}"
        - name: resources.limits.cpu
          value: "{{ .Values.cpu }}m"
        - name: resources.limits.memory
          value: "{{ .Values.memory }}Mi"
        - name: resources.requests.cpu
          value: "{{ .Values.cpu }}m"
        - name: resources.requests.memory
          value: "{{ .Values.memory }}Mi"
        - name: esJavaOpts
<<<<<<< HEAD
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ percent .Values.memory .Values.heap_percent
            }}m -Xmx{{ percent .Values.memory .Values.heap_percent }}m"
=======
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ percent .Values.memory .Values.heap_percent}}m -Xmx{{ percent .Values.memory .Values.heap_percent }}m"
>>>>>>> e2beec7 (feat: migrate examples to 2.0 CRDs using stormforge fix command)
        - name: persistence.enabled
          value: "false"
        - name: antiAffinity
          value: soft
