---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elasticsearch-example
rules:
- resources:
  - statefulsets
  apiGroups:
  - apps
  verbs:
  - get
- resources:
  - pods
  apiGroups:
  - ""
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elasticsearch-example
roleRef:
  name: elasticsearch-example
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: optimize-pro-controller
  namespace: stormforge-system
  kind: ServiceAccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-example-setup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elasticsearch-example-setup
rules:
- resources:
  - replicasets
  apiGroups:
  - apps
  verbs:
  - list
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - create
  - delete
  - list
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elasticsearch-example-setup
roleRef:
  name: elasticsearch-example-setup
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: elasticsearch-example-setup
  kind: ServiceAccount
