apiVersion: v1
kind: Service
metadata:
  name: hello-world-121-nginx
spec:
  selector:
    app.kubernetes.io/name: hello-world-121-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-121-nginx
  labels:
    app.kubernetes.io/name: hello-world-121-nginx
    stormforge.io/application: 'hello-world'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world-121-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world-121-nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx:latest
        env:
        - name: VARIABLE
          value: "10"
        command: ['/bin/sh', '-c', 'echo $(VARIABLE) > /usr/share/nginx/html/variable && nginx -g "daemon off;"']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: optimize-pro-setuptask-crb
  labels:
    stormforge.io/application: 'hello-world'
roleRef:
  name: optimize-pro-setuptask-cr
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: optimize-pro-setuptask-sa
  namespace: default # ENSURE CORRECT VALUE FOR SERVICE_ACCOUNT
  kind: ServiceAccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: optimize-pro-setuptask-sa
  namespace: default # ENSURE SAME VALUE AS CLUSTER_ROLE_BINDING
  labels:
    stormforge.io/application: 'hello-world'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optimize-pro-setuptask-cr
  labels:
    stormforge.io/application: 'hello-world'
rules:
- resources:
  - clusterroles
  - clusterrolebindings
  apiGroups:
  - rbac.authorization.k8s.io
  verbs:
  - get
  - create
  - delete
- resources:
  - serviceaccounts
  - services
  - configmaps
  apiGroups:
  - ""
  verbs:
  - get
  - create
  - delete
- resources:
  - deployments
  apiGroups:
  - apps
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  apiGroups:
  - ""
  verbs:
  - list
  - watch
  - get
- resources:
  - pods
  - pods/log
  - pods/exec
  apiGroups:
  - ""
  verbs:
  - list
  - get
  - watch
  - create
- resources:
  - jobs
  apiGroups:
  - batch
  verbs:
  - create
  - get
  - list
  - watch
