---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: optimize-pro-setuptask-crb
roleRef:
  name: optimize-pro-setuptask-cr
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: optimize-pro-setuptask-sa
  namespace: default # ENSURE CORRECT VALUE FOR SERVICE_ACCOUNT
  kind: ServiceAccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: optimize-pro-setuptask-sa
  namespace: default # ENSURE SAME VALUE AS CLUSTER_ROLE_BINDING
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optimize-pro-setuptask-cr
rules:
- resources:
  - clusterroles
  - clusterrolebindings
  apiGroups:
  - rbac.authorization.k8s.io
  verbs:
  - get
  - create
  - delete
- resources:
  - serviceaccounts
  - services
  - configmaps
  apiGroups:
  - ""
  verbs:
  - get
  - create
  - delete
- resources:
  - deployments
  apiGroups:
  - apps
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  apiGroups:
  - ""
  verbs:
  - list
  - watch
  - get
- resources:
  - pods
  - pods/log
  - pods/exec
  apiGroups:
  - ""
  verbs:
  - list
  - get
  - watch
  - create
- resources:
  - jobs
  apiGroups:
  - batch
  verbs:
  - create
  - get
  - list
  - watch
