apiVersion: redskyops.dev/v1beta1
kind: Experiment
metadata:
  labels:
    redskyops.dev/application: hpa-sf
    redskyops.dev/scenario: standard
  name: hpa-sf
spec:
  metrics:
  - minimize: true
    name: cost
    port: 9090
    query: ({{ cpuRequests . "" }} * 17) + ({{ memoryRequests . "" | GB }} * 3)
    type: prometheus
  - minimize: true
    name: error_ratio
    port: 9090
    query: scalar(error_ratio{job="trialRun",instance="{{ .Trial.Name }}"})
    type: prometheus
  - minimize: true
    optimize: false
    name: p95-latency
    port: 9090
    query: scalar(percentile_95{job="trialRun",instance="{{ .Trial.Name }}"})
    type: prometheus
  - minimize: true
    name: p50-latency
    optimize: false
    port: 9090
    query: scalar(median{job="trialRun",instance="{{ .Trial.Name }}"})
    type: prometheus
  - minimize: true
    max: "1000"
    name: p99-latency
    optimize: false
    port: 9090
    query: scalar(percentile_99{job="trialRun",instance="{{ .Trial.Name }}"})
    type: prometheus
  parameters:
  - baseline: 2098
    max: 4096
    min: 128
    name: memory
  - baseline: 1000
    max: 4000
    min: 100
    name: cpu
  - name: min_replicas
    min: 1
    max: 4
    baseline: 2
  - name: max_replicas
    min: 1
    max: 4
    baseline: 2
  - name: avg_utilization
    min: 10
    max: 80
    baseline: 50
  constraints:
    - order:
        lowerParameter: min_replicas
        upperParameter: max_replicas
  patches:
  - targetRef:
      kind: HorizontalPodAutoscaler
      apiVersion: autoscaling/v2beta2
      name: voting-hpa
    patch: |
      spec:
        maxReplicas: {{ .Values.max_replicas }}
        minReplicas: {{ .Values.min_replicas }}
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: {{ .Values.avg_utilization }}
  - patch: |
      spec:
        template:
          spec:
            containers:
            - name: voting-service
              resources:
                limits:
                  memory: '{{ .Values.memory }}M'
                  cpu: '{{ .Values.cpu }}m'
                requests:
                  memory: '{{ .Values.memory }}M'
                  cpu: '{{ .Values.cpu }}m'
    targetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: voting-service
  trialTemplate:
    metadata:
      labels:
        redskyops.dev/application: hpa-sf
        redskyops.dev/scenario: standard
    spec:
      jobTemplate:
        metadata:
          labels:
            redskyops.dev/application: hpa-sf
            redskyops.dev/scenario: standard
        spec:
          template:
            metadata:
              labels:
                redskyops.dev/application: hpa-sf
                redskyops.dev/scenario: standard
            spec:
              containers:
              - env:
                - name: TITLE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: TEST_CASE
                  value: sf_sandbox/hpa-sf-standard
                - name: TEST_CASE_FILE
                  value: /forge-init.d/testcase.js
                - name: TARGET
                  value: http://my-url-example.com
                - name: STORMFORGER_JWT
                  valueFrom:
                    secretKeyRef:
                      key: accessToken
                      name: stormforger-service-account
                image: thestormforge/optimize-trials:v0.0.1-stormforger
                name: stormforger
                resources: {}
                volumeMounts:
                - mountPath: /forge-init.d
                  name: test-case-file
                  readOnly: true
              volumes:
              - configMap:
                  name: standard-test-case-file
                name: test-case-file
      setupServiceAccountName: redsky-setup
      setupTasks:
      - args:
        - prometheus
        - $(MODE)
        name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    redskyops.dev/application: hpa-sf
  name: redsky-setup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    redskyops.dev/application: hpa-sf
  name: redsky-prometheus
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  - configmaps
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    redskyops.dev/application: hpa-sf
  name: redsky-setup-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redsky-prometheus
subjects:
- kind: ServiceAccount
  name: redsky-setup

