apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hpa-sf

resources:
# - sfjwt.yaml
- experiment.yaml

configMapGenerator:
- name: standard-test-case-file
  files:
  - testcase.js

secretGenerator:
- name: stormforger-service-account
  files:
  - accessToken

generatorOptions:
  disableNameSuffixHash: true