---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stormforge-setup
  labels:
    stormforge.io/application: 'stormforger-testapp'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stormforge-prometheus
  labels:
    stormforge.io/application: 'stormforger-testapp'
rules:
- resources:
  - clusterroles
  - clusterrolebindings
  apiGroups:
  - rbac.authorization.k8s.io
  verbs:
  - get
  - create
  - delete
- resources:
  - serviceaccounts
  - services
  - configmaps
  apiGroups:
  - ""
  verbs:
  - get
  - create
  - delete
- resources:
  - deployments
  apiGroups:
  - apps
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  apiGroups:
  - ""
  verbs:
  - list
  - watch
  - get
- resources:
  - pods
  apiGroups:
  - ""
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stormforge-setup-prometheus
  labels:
    stormforge.io/application: 'stormforger-testapp'
roleRef:
  name: stormforge-prometheus
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: stormforge-setup
  kind: ServiceAccount
  namespace: default