apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../voting-webapp/application
- experiment.yaml

- path: ./owner_references_patch.yaml
  target:
    group: optimize.stormforge.io
    version: v1beta2
    kind: Experiment
