apiVersion: apps.optimize.stormforge.io/v1alpha1
kind: Application
metadata:
  name: postgres
resources:
- postgres.yaml
configuration:
- containerResources:
    selector: >-
      app.kubernetes.io/instance=postgres-stormforge-example, app.kubernetes.io/name=postgres
scenarios:
- custom:
    initialDelaySeconds: 15
    podTemplate:
      spec:
        initContainers:
        - name: pgbench-initialize
          image: postgres:11.1-alpine
          command:
          - /usr/local/bin/pgbench
          args:
          - --initialize
          - --host=$(PG_HOSTNAME)
          - --username=$(PG_USERNAME)
          - --scale=$(PGBENCH_SCALE)
          - $(PG_DATABASE)
          envFrom:
          - secretRef:
              name: postgres-secret
        containers:
        - name: pgbench
          image: postgres:11.1-alpine
          command:
          - /usr/local/bin/pgbench
          args:
          - --client=$(PGBENCH_CLIENTS)
          - --jobs=$(PGBENCH_JOBS)
          - --scale=$(PGBENCH_SCALE)
          - --transactions=$(PGBENCH_TRANSACTIONS)
          - --host=$(PG_HOSTNAME)
          - --username=$(PG_USERNAME)
          - $(PG_DATABASE)
          envFrom:
          - secretRef:
              name: postgres-secret
objectives:
- goals:
  - name: duration
  - name: cost
    requests:
      selector: >-
        app.kubernetes.io/instance=postgres-stormforge-example, app.kubernetes.io/name=postgres
