apiVersion: redskyops.dev/v1alpha1
kind: Experiment
metadata:
  name: postgres-example
spec:
  optimization:
  - name: "experimentBudget"
    value: "40" #number of trials
  parameters:
  - name: memory
    min: 500
    max: 4000
    baseline: 4000
  - name: cpu
    min: 100
    max: 4000
    baseline: 4000
  metrics:
  - name: duration
    minimize: true
    query: "{{duration .StartTime .CompletionTime}}"
  - name: cost
    minimize: true
    type: pods
    # Note that these cost weights are specific to GKE and represent $22/month/cpu and $3/month/GB
    query: '{{resourceRequests .Pods "cpu=0.022,memory=0.000000000003"}}'
    selector:
      matchLabels:
        component: postgres
  patches:
  - targetRef:
      kind: Deployment
      apiVersion: apps/v1
      name: postgres
    patch: |
      spec:
        template:
          spec:
            containers:
            - name: postgres
              resources:
                limits:
                  cpu: "{{ .Values.cpu }}m"
                  memory: "{{ .Values.memory }}Mi"
                requests:
                  cpu: "{{ .Values.cpu }}m"
                  memory: "{{ .Values.memory }}Mi"
  template: # trial
    spec:
      initialDelaySeconds: 15
      template: # job
        spec:
          template: # pod
            spec:
              containers:
              - image: crunchydata/crunchy-pgbench:centos7-11.4-2.4.1
                name: pgbench
                envFrom:
                - secretRef:
                    name: postgres-secret
