apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app.kubernetes.io/instance: postgres-stormforge-example
    app.kubernetes.io/name: postgres
stringData:
  PGBENCH_CLIENTS: "5"
  PGBENCH_JOBS: "10"
  PGBENCH_SCALE: "20"
  PGBENCH_TRANSACTIONS: "10000"
  PG_DATABASE: "test_db"
  PG_HOSTNAME: "postgres"
  PG_PASSWORD: "test_password"
  PGPASSWORD: "test_password"
  PG_USERNAME: "test_user"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/instance: postgres-stormforge-example
    app.kubernetes.io/name: postgres
spec:
  selector:
    app.kubernetes.io/instance: postgres-stormforge-example
    app.kubernetes.io/name: postgres
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app.kubernetes.io/instance: postgres-stormforge-example
    app.kubernetes.io/name: postgres
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: postgres-stormforge-example
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: postgres-stormforge-example
        app.kubernetes.io/name: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11.1-alpine
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PG_DATABASE
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PG_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PG_PASSWORD
        resources:
          limits:
            cpu: 4.0
            memory: 4096M
          requests:
            cpu: 4.0
            memory: 4096M
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - test_user
            - -d
            - test_db
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          tcpSocket:
            port: 5432
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 70 # postgres user on Alpine
      volumes:
      - name: postgres-storage
        emptyDir: {}
  strategy:
    type: Recreate
