---
apiVersion: optimize.stormforge.io/v1beta2
kind: Experiment
metadata:
  name: hpa-example
  annotations:
    config.kubernetes.io/path: 'experiment.yaml'
spec:
  parameters:
  - name: voting_cpu
    baseline: 400
    min: 100
    max: 1000
  - name: min_replicas
    baseline: 1
    min: 1
    max: 4
  - name: max_replicas
    baseline: 2
    min: 1
    max: 4
  - name: avg_utilization
    baseline: 50
    min: 10
    max: 80
  constraints:
  - order:
      lowerParameter: min_replicas
      upperParameter: max_replicas
  metrics:
  - name: p95-latency
    type: prometheus
    max: "1300"
    minimize: true
    query: scalar(p95{job="trialRun",instance="{{ .Trial.Name }}"})
  - name: cost-gcp
    type: prometheus
    minimize: true
    query: ({{ cpuRequests . "" }} * 17) + ({{ memoryRequests . "" | GB }} * 2)
  - name: failures_per_s
    type: prometheus
    minimize: true
    optimize: false
    query: scalar(failures_per_s{job="trialRun",instance="{{ .Trial.Name }}"})
  patches:
  - targetRef:
      name: voting-service
      apiVersion: apps/v1
      kind: Deployment
    patch: |
      spec:
        replicas: {{ .Values.min_replicas }}
        template:
          spec:
            containers:
            - name: voting-service
              resources:
                limits:
                  cpu: "{{ .Values.voting_cpu }}m"
                  memory: "250Mi"
                requests:
                  cpu: "{{ .Values.voting_cpu }}m"
                  memory: "250Mi"
  - targetRef:
      name: voting-hpa
      apiVersion: autoscaling/v2beta2
      kind: HorizontalPodAutoscaler
    patch: |
      spec:
        maxReplicas: {{ .Values.max_replicas }}
        minReplicas: {{ .Values.min_replicas }}
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: {{ .Values.avg_utilization }}
  trialTemplate:
    spec:
      setupTasks:
      - name: prometheus
        helmChart: oci://registry.stormforge.io/optimize-pro/prometheus
      jobTemplate:
        spec:
          template:
            spec:
              containers:
              - name: locust
                image: thestormforge/optimize-trials:v0.0.1-locust
                env:
                - name: HOST
                  value: http://voting-service
                - name: NUM_USERS
                  value: "500"
                - name: SPAWN_RATE
                  value: "50"
                - name: RUN_TIME
                  value: "180"
                resources:
                  requests:
                    cpu: "1"
                volumeMounts:
                - name: locustfile
                  readOnly: true
                  mountPath: /mnt/locust
              volumes:
              - name: locustfile
                configMap:
                  name: locustfile
