apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recipe

resources:
  - ../../webapp/voting-webapp/application/manifests
  - hpa.yaml
  - experiment.yaml

configMapGenerator:
- name: locustfile
  files:
  - locustfile.py

generatorOptions:
  disableNameSuffixHash: true
