---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpa-example
rules:
- resources:
  - deployments
  apiGroups:
  - apps
  verbs:
  - get
  - patch
- resources:
  - horizontalpodautoscalers
  apiGroups:
  - autoscaling
  verbs:
  - get
  - patch
- resources:
  - pods
  apiGroups:
  - ""
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-example
roleRef:
  name: hpa-example
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: optimize-pro-controller
  namespace: stormforge-system
  kind: ServiceAccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpa-example-setup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpa-example-setup
rules:
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - create
  - delete
  - list
  - get
  - update
- resources:
  - replicasets
  apiGroups:
  - apps
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-example-setup
roleRef:
  name: hpa-example-setup
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: hpa-example-setup
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optimize-prometheus-b344ee
rules:
- resources:
  - clusterroles
  - clusterrolebindings
  apiGroups:
  - rbac.authorization.k8s.io
  verbs:
  - get
  - create
  - delete
- resources:
  - serviceaccounts
  - services
  - configmaps
  apiGroups:
  - ""
  verbs:
  - get
  - create
  - delete
- resources:
  - deployments
  apiGroups:
  - apps
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  apiGroups:
  - ""
  verbs:
  - list
  - watch
  - get
- resources:
  - pods
  apiGroups:
  - ""
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: optimize-setup-prometheus-b344ee
roleRef:
  name: optimize-prometheus-b344ee
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: hpa-example-setup
  namespace: default
  kind: ServiceAccount
